name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
      with:
        node-version: 20.x
    - run: yarn install --frozen-lockfile
    - run: yarn run lint:prettier
    - run: yarn run lint
    - run: yarn run typecheck
    - run: yarn run test:unit
    - run: yarn run build
    - run: yarn run test:package-types
